#!/bin/bash

# Get document root path
DOCUMENT_ROOT=$(drush status --fields=root --format=list)

# Git repo root
cd $DOCUMENT_ROOT
cd ..

sudo chown -R $USER:www-data web/sites/default/files/
sudo chmod -R g+w web/sites/default/files/

sudo chown $USER:$USER web/sites/default/settings.*
sudo chmod g-w web/sites/default/settings.*

sudo chown -R $USER:www-data config
sudo chmod -R g+w config

sudo chown -R $USER:www-data private
sudo chmod -R g+w private
